apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
      - image: olivercw/resultserver
        name: resultserver
        ports: 
        - containerPort: 3000
        # envFrom:
        #   - secretRef:
        #       name: mysql-secret
        #   - configMapRef:
        #       name: server-configmap
        env: 
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: mysql-database-host
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: mysql-database

        resources: {}
