apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: MTIzNDU2QWE=
  mysql-password: MjgxNTAyRGU=
  mysql-user: ZW1yZQ==  # bu üç satır env ile kullanımda kullanılır.

  # MYSQL_ROOT_PASSWORD: MTIzNDU2QWE=
  # MYSQL_PASSWORD: MjgxNTAyRGU= #bu iki satır da envFrom da kullanılır.
  # MYSQL_USER: ZW1yZQ==
  

